=== andricDu/argo-meta-dictionary/argoMetaSchema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "ARGO File Meta Schema",
    "definitions": {
        "stringRestrictions": {
            "type": "object",
            "properties": {
                "required": {
                    "type": "object",
                    "required": [
                        "default"
                    ],
                    "properties": {
                        "default": {
                            "type": "string"
                        }
                    },
                    "additionalProperties": false
                },
                "codeList": {
                    "type": "array",
                    "minItems": 2,
                    "uniqueItems": true,
                    "items": {
                        "type": "string"
                    }
                },
                "script": {
                    "type": "string"
                },
                "foreignKey": {
                    "type": "object",
                    "required": ["entityName", "fieldName"],
                    "properties": {
                        "entityName": {
                            "type": "string"
                        },
                        "fieldName": {
                            "type": "string"
                        }
                    },
                    "additionalProperties": false
                },
                "unique": {
                    "type": "boolean"
                }
            },
            "additionalProperties": false
        },
        "integerRestrictions": {
            "type": "object",
            "properties": {
                "required": {
                    "type": "object",
                    "required": [
                        "default"
                    ],
                    "properties": {
                        "default": {
                            "type": "integer"
                        }
                    },
                    "additionalProperties": false
                },
                "script": {
                    "type": "string"
                }
            },
            "additionalProperties": false
        },
        "numberRestrictions": {
            "type": "object",
            "properties": {
                "required": {
                    "type": "object",
                    "required": [
                        "default"
                    ],
                    "properties": {
                        "default": {
                            "type": "number"
                        }
                    },
                    "additionalProperties": false
                },
                "script": {
                    "type": "string"
                }
            },
            "additionalProperties": false
        },
        "booleanRestrictions": {
            "type": "object",
            "properties": {
                "required": {
                    "type": "object",
                    "required": [
                        "default"
                    ],
                    "properties": {
                        "default": {
                            "type": "boolean"
                        }
                    },
                    "additionalProperties": false
                },
                "script": {
                    "type": "string"
                }
            },
            "additionalProperties": false
        },
        "field": {
            "type": "object",
            "required": [
                "name",
                "description",
                "valueType"
            ],
            "properties": {
                "name": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "valueType": {
                    "type": "string",
                    "enum": [
                        "string",
                        "integer",
                        "number",
                        "boolean"
                    ]
                },
                "default": {
                    "type": ["string", "integer", "number", "boolean"]
                },
                "restrictions": {
                    "anyOf": [
                        {
                            "$ref": "#/definitions/stringRestrictions"
                        },
                        {
                            "$ref": "#/definitions/integerRestrictions"
                        },
                        {
                            "$ref": "#/definitions/numberRestrictions"
                        },
                        {
                            "$ref": "#/definitions/booleanRestrictions"
                        }
                    ]
                }
            },
            "oneOf" : [
                {
                    "properties": {
                        "valueType": {"const": "string"},
                        "restrictions": {"$ref": "#/definitions/stringRestrictions"}
                    }
                }
            ],
            "anyOf": [
                {
                    "properties": {
                        "valueType": {"const": "string"},
                        "restrictions": {"$ref": "#/definitions/stringRestrictions"}
                    }
                },
                {
                    "properties": {
                        "valueType": {"const": "integer"},
                        "restrictions": {"$ref": "#/definitions/integerRestrictions"}
                    }
                },
                {
                    "properties": {
                        "valueType": {"const": "number"},
                        "restrictions": {"$ref": "#/definitions/numberRestrictions"}
                    }
                },
                {
                    "properties": {
                        "valueType": {"const": "boolean"},
                        "restrictions": {"$ref": "#/definitions/booleanRestrictions"}
                    }
                }
            ],
            "additionalProperties": false
        }
    },
    "required": [
        "name",
        "description",
        "key",
        "fields"
    ],
    "properties": {
        "name": {
            "type": "string"
        },
        "description": {
            "type": "string"
        },
        "key": {
            "type": "string"
        },
        "fields": {
            "type": "array",
            "minItems": 3,
            "uniqueItems": true,
            "items": {
                "$ref": "#/definitions/field"
            }
        }
    },
    "additionalProperties": false
}

=== andricDu/argo-meta-dictionary/donorSchema.json
{
    "name": "donor",
    "description": "Donor Entity",
    "key": "donor_submitter_id",
    "fields": [
        {
            "name": "donor_submitter_id",
            "valueType": "string",
            "description": "Unique identifier for donor; assigned by data provider",
            "default": "MISSING",
            "restrictions": {
                "unique": true,
                "required": {
                    "default": "MISSING"
                },
                "script": "field.length > 5"
            }
        },
        {
            "name": "gender",
            "valueType": "string",
            "description": "Donor Biological Sex",
            "restrictions": {
                "codeList": [
                    "Male",
                    "Female",
                    "Other"
                ]
            }
        },
        {
            "name": "ethnicity",
            "valueType": "string",
            "description": "Self described",
            "restrictions": {}
        },
        {
            "name": "vital_status",
            "valueType": "string",
            "description": "Donor's last known vital status",
            "restrictions": {
                "required": {
                    "default": "Other"
                },
                "codeList": [
                    "Alive",
                    "Deceased",
                    "Other"
                ]
            }
        },
        {
            "name": "cause_of_death",
            "valueType": "string",
            "description": "Cause of Donor Death",
            "restrictions": {}
        }
    ]
}
